# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'snuslock.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(824, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.button_frame = QtWidgets.QFrame(self.centralwidget)
        self.button_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.button_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.button_frame.setObjectName("button_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.button_frame)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_inleverera = QtWidgets.QPushButton(self.button_frame)
        self.pushButton_inleverera.setObjectName("pushButton_inleverera")
        self.gridLayout.addWidget(self.pushButton_inleverera, 0, 0, 1, 1)
        self.pushButton_mottaget = QtWidgets.QPushButton(self.button_frame)
        self.pushButton_mottaget.setObjectName("pushButton_mottaget")
        self.gridLayout.addWidget(self.pushButton_mottaget, 1, 3, 1, 1)
        self.pushButton_statistik = QtWidgets.QPushButton(self.button_frame)
        self.pushButton_statistik.setObjectName("pushButton_statistik")
        self.gridLayout.addWidget(self.pushButton_statistik, 1, 1, 1, 1)
        self.pushButton_smaker = QtWidgets.QPushButton(self.button_frame)
        self.pushButton_smaker.setObjectName("pushButton_smaker")
        self.gridLayout.addWidget(self.pushButton_smaker, 1, 0, 1, 1)
        self.pushButton_fakturera = QtWidgets.QPushButton(self.button_frame)
        self.pushButton_fakturera.setObjectName("pushButton_fakturera")
        self.gridLayout.addWidget(self.pushButton_fakturera, 0, 3, 1, 1)
        self.verticalLayout_3.addWidget(self.button_frame)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_lager = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_lager.setFont(font)
        self.label_lager.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_lager.setText("Lager")
        self.label_lager.setTextFormat(QtCore.Qt.RichText)
        self.label_lager.setAlignment(QtCore.Qt.AlignCenter)
        self.label_lager.setObjectName("label_lager")
        self.horizontalLayout_3.addWidget(self.label_lager)
        self.toolButton_add_Lager = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_add_Lager.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/contact-new.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_add_Lager.setIcon(icon)
        self.toolButton_add_Lager.setObjectName("toolButton_add_Lager")
        self.horizontalLayout_3.addWidget(self.toolButton_add_Lager)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tableWidget_lager = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_lager.sizePolicy().hasHeightForWidth())
        self.tableWidget_lager.setSizePolicy(sizePolicy)
        self.tableWidget_lager.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_lager.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_lager.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_lager.setTabKeyNavigation(False)
        self.tableWidget_lager.setProperty("showDropIndicator", False)
        self.tableWidget_lager.setDragDropOverwriteMode(False)
        self.tableWidget_lager.setShowGrid(False)
        self.tableWidget_lager.setCornerButtonEnabled(False)
        self.tableWidget_lager.setRowCount(0)
        self.tableWidget_lager.setColumnCount(2)
        self.tableWidget_lager.setObjectName("tableWidget_lager")
        self.tableWidget_lager.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_lager.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget_lager.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_lager.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableWidget_lager)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_utleverera = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_utleverera.sizePolicy().hasHeightForWidth())
        self.pushButton_utleverera.setSizePolicy(sizePolicy)
        self.pushButton_utleverera.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_utleverera.setObjectName("pushButton_utleverera")
        self.horizontalLayout_2.addWidget(self.pushButton_utleverera)
        self.label_total = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_total.sizePolicy().hasHeightForWidth())
        self.label_total.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_total.setFont(font)
        self.label_total.setObjectName("label_total")
        self.horizontalLayout_2.addWidget(self.label_total)
        self.label_totalCount = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_totalCount.setFont(font)
        self.label_totalCount.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_totalCount.setTextFormat(QtCore.Qt.RichText)
        self.label_totalCount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_totalCount.setObjectName("label_totalCount")
        self.horizontalLayout_2.addWidget(self.label_totalCount)
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame1 = QtWidgets.QFrame(self.frame_2)
        self.frame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame1.setLineWidth(1)
        self.frame1.setMidLineWidth(0)
        self.frame1.setObjectName("frame1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_years = QtWidgets.QComboBox(self.frame1)
        self.comboBox_years.setObjectName("comboBox_years")
        self.comboBox_years.addItem("")
        self.comboBox_years.addItem("")
        self.comboBox_years.addItem("")
        self.comboBox_years.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_years)
        self.pushButton_monthyStats = QtWidgets.QPushButton(self.frame1)
        self.pushButton_monthyStats.setObjectName("pushButton_monthyStats")
        self.horizontalLayout.addWidget(self.pushButton_monthyStats)
        self.pushButton_weeklyStats = QtWidgets.QPushButton(self.frame1)
        self.pushButton_weeklyStats.setObjectName("pushButton_weeklyStats")
        self.horizontalLayout.addWidget(self.pushButton_weeklyStats)
        self.verticalLayout_2.addWidget(self.frame1)
        self.tabWidget = QtWidgets.QTabWidget(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidgetPage_monthly = QtWidgets.QWidget()
        self.tabWidgetPage_monthly.setObjectName("tabWidgetPage_monthly")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tabWidgetPage_monthly)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tableView_monthly = QtWidgets.QTableView(self.tabWidgetPage_monthly)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView_monthly.sizePolicy().hasHeightForWidth())
        self.tableView_monthly.setSizePolicy(sizePolicy)
        self.tableView_monthly.setObjectName("tableView_monthly")
        self.horizontalLayout_5.addWidget(self.tableView_monthly)
        self.tabWidget.addTab(self.tabWidgetPage_monthly, "")
        self.tabWidgetPage_weekly = QtWidgets.QWidget()
        self.tabWidgetPage_weekly.setObjectName("tabWidgetPage_weekly")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tabWidgetPage_weekly)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tableView_weekly = QtWidgets.QTableView(self.tabWidgetPage_weekly)
        self.tableView_weekly.setObjectName("tableView_weekly")
        self.verticalLayout_5.addWidget(self.tableView_weekly)
        self.tabWidget.addTab(self.tabWidgetPage_weekly, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout_4.addWidget(self.frame_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 824, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Quit = QtWidgets.QAction(MainWindow)
        self.action_Quit.setObjectName("action_Quit")
        self.actionOpen_Smaker = QtWidgets.QAction(MainWindow)
        self.actionOpen_Smaker.setObjectName("actionOpen_Smaker")
        self.action_Importera = QtWidgets.QAction(MainWindow)
        self.action_Importera.setObjectName("action_Importera")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Importera)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Quit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Snuslock"))
        self.pushButton_inleverera.setText(_translate("MainWindow", "Inleverera"))
        self.pushButton_mottaget.setText(_translate("MainWindow", "Mottaget"))
        self.pushButton_statistik.setText(_translate("MainWindow", "Statistik"))
        self.pushButton_smaker.setText(_translate("MainWindow", "Smaker"))
        self.pushButton_fakturera.setText(_translate("MainWindow", "Fakturera"))
        self.toolButton_add_Lager.setToolTip(_translate("MainWindow", "Lägg till i lager"))
        self.pushButton_utleverera.setText(_translate("MainWindow", "Utleverara"))
        self.label_total.setText(_translate("MainWindow", "Totalt:"))
        self.label_totalCount.setText(_translate("MainWindow", "0"))
        self.comboBox_years.setItemText(0, _translate("MainWindow", "2017"))
        self.comboBox_years.setItemText(1, _translate("MainWindow", "2018"))
        self.comboBox_years.setItemText(2, _translate("MainWindow", "2019"))
        self.comboBox_years.setItemText(3, _translate("MainWindow", "2020"))
        self.pushButton_monthyStats.setText(_translate("MainWindow", "Månadsvis statistik"))
        self.pushButton_weeklyStats.setText(_translate("MainWindow", "Veckovis statistik"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage_monthly), _translate("MainWindow", "Månadsvis"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage_weekly), _translate("MainWindow", "Veckovis"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.action_Quit.setText(_translate("MainWindow", "&Stäng"))
        self.actionOpen_Smaker.setText(_translate("MainWindow", "open_Smaker"))
        self.action_Importera.setText(_translate("MainWindow", "&Importera"))

import snuslock_rc
